[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
dynamic_padding = true
decorations = "none"
opacity = 0.95
startup_mode = "Fullscreen"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
